// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	mock "github.com/stretchr/testify/mock"
)

// NewMockBaseBranchResolver creates a new instance of MockBaseBranchResolver. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockBaseBranchResolver(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockBaseBranchResolver {
	mock := &MockBaseBranchResolver{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockBaseBranchResolver is an autogenerated mock type for the BaseBranchResolver type
type MockBaseBranchResolver struct {
	mock.Mock
}

type MockBaseBranchResolver_Expecter struct {
	mock *mock.Mock
}

func (_m *MockBaseBranchResolver) EXPECT() *MockBaseBranchResolver_Expecter {
	return &MockBaseBranchResolver_Expecter{mock: &_m.Mock}
}

// ResolveBaseBranch provides a mock function for the type MockBaseBranchResolver
func (_mock *MockBaseBranchResolver) ResolveBaseBranch(repoPath string) (string, error) {
	ret := _mock.Called(repoPath)

	if len(ret) == 0 {
		panic("no return value specified for ResolveBaseBranch")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) (string, error)); ok {
		return returnFunc(repoPath)
	}
	if returnFunc, ok := ret.Get(0).(func(string) string); ok {
		r0 = returnFunc(repoPath)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(repoPath)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockBaseBranchResolver_ResolveBaseBranch_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ResolveBaseBranch'
type MockBaseBranchResolver_ResolveBaseBranch_Call struct {
	*mock.Call
}

// ResolveBaseBranch is a helper method to define mock.On call
//   - repoPath string
func (_e *MockBaseBranchResolver_Expecter) ResolveBaseBranch(repoPath interface{}) *MockBaseBranchResolver_ResolveBaseBranch_Call {
	return &MockBaseBranchResolver_ResolveBaseBranch_Call{Call: _e.mock.On("ResolveBaseBranch", repoPath)}
}

func (_c *MockBaseBranchResolver_ResolveBaseBranch_Call) Run(run func(repoPath string)) *MockBaseBranchResolver_ResolveBaseBranch_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockBaseBranchResolver_ResolveBaseBranch_Call) Return(s string, err error) *MockBaseBranchResolver_ResolveBaseBranch_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *MockBaseBranchResolver_ResolveBaseBranch_Call) RunAndReturn(run func(repoPath string) (string, error)) *MockBaseBranchResolver_ResolveBaseBranch_Call {
	_c.Call.Return(run)
	return _c
}
