// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	mock "github.com/stretchr/testify/mock"
)

// NewMockClipboardWriter creates a new instance of MockClipboardWriter. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockClipboardWriter(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockClipboardWriter {
	mock := &MockClipboardWriter{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockClipboardWriter is an autogenerated mock type for the ClipboardWriter type
type MockClipboardWriter struct {
	mock.Mock
}

type MockClipboardWriter_Expecter struct {
	mock *mock.Mock
}

func (_m *MockClipboardWriter) EXPECT() *MockClipboardWriter_Expecter {
	return &MockClipboardWriter_Expecter{mock: &_m.Mock}
}

// WriteClipboard provides a mock function for the type MockClipboardWriter
func (_mock *MockClipboardWriter) WriteClipboard(ctx context.Context, text string) error {
	ret := _mock.Called(ctx, text)

	if len(ret) == 0 {
		panic("no return value specified for WriteClipboard")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = returnFunc(ctx, text)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockClipboardWriter_WriteClipboard_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'WriteClipboard'
type MockClipboardWriter_WriteClipboard_Call struct {
	*mock.Call
}

// WriteClipboard is a helper method to define mock.On call
//   - ctx context.Context
//   - text string
func (_e *MockClipboardWriter_Expecter) WriteClipboard(ctx interface{}, text interface{}) *MockClipboardWriter_WriteClipboard_Call {
	return &MockClipboardWriter_WriteClipboard_Call{Call: _e.mock.On("WriteClipboard", ctx, text)}
}

func (_c *MockClipboardWriter_WriteClipboard_Call) Run(run func(ctx context.Context, text string)) *MockClipboardWriter_WriteClipboard_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockClipboardWriter_WriteClipboard_Call) Return(err error) *MockClipboardWriter_WriteClipboard_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockClipboardWriter_WriteClipboard_Call) RunAndReturn(run func(ctx context.Context, text string) error) *MockClipboardWriter_WriteClipboard_Call {
	_c.Call.Return(run)
	return _c
}
