// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	mock "github.com/stretchr/testify/mock"
)

// NewMockFileContentReader creates a new instance of MockFileContentReader. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockFileContentReader(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockFileContentReader {
	mock := &MockFileContentReader{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockFileContentReader is an autogenerated mock type for the FileContentReader type
type MockFileContentReader struct {
	mock.Mock
}

type MockFileContentReader_Expecter struct {
	mock *mock.Mock
}

func (_m *MockFileContentReader) EXPECT() *MockFileContentReader_Expecter {
	return &MockFileContentReader_Expecter{mock: &_m.Mock}
}

// ReadFileLines provides a mock function for the type MockFileContentReader
func (_mock *MockFileContentReader) ReadFileLines(repoPath string, path string) ([]string, error) {
	ret := _mock.Called(repoPath, path)

	if len(ret) == 0 {
		panic("no return value specified for ReadFileLines")
	}

	var r0 []string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string, string) ([]string, error)); ok {
		return returnFunc(repoPath, path)
	}
	if returnFunc, ok := ret.Get(0).(func(string, string) []string); ok {
		r0 = returnFunc(repoPath, path)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string, string) error); ok {
		r1 = returnFunc(repoPath, path)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockFileContentReader_ReadFileLines_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ReadFileLines'
type MockFileContentReader_ReadFileLines_Call struct {
	*mock.Call
}

// ReadFileLines is a helper method to define mock.On call
//   - repoPath string
//   - path string
func (_e *MockFileContentReader_Expecter) ReadFileLines(repoPath interface{}, path interface{}) *MockFileContentReader_ReadFileLines_Call {
	return &MockFileContentReader_ReadFileLines_Call{Call: _e.mock.On("ReadFileLines", repoPath, path)}
}

func (_c *MockFileContentReader_ReadFileLines_Call) Run(run func(repoPath string, path string)) *MockFileContentReader_ReadFileLines_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockFileContentReader_ReadFileLines_Call) Return(strings []string, err error) *MockFileContentReader_ReadFileLines_Call {
	_c.Call.Return(strings, err)
	return _c
}

func (_c *MockFileContentReader_ReadFileLines_Call) RunAndReturn(run func(repoPath string, path string) ([]string, error)) *MockFileContentReader_ReadFileLines_Call {
	_c.Call.Return(run)
	return _c
}
