// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"ero/internal/ports"

	mock "github.com/stretchr/testify/mock"
)

// NewMockGitMetadataReader creates a new instance of MockGitMetadataReader. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockGitMetadataReader(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockGitMetadataReader {
	mock := &MockGitMetadataReader{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockGitMetadataReader is an autogenerated mock type for the GitMetadataReader type
type MockGitMetadataReader struct {
	mock.Mock
}

type MockGitMetadataReader_Expecter struct {
	mock *mock.Mock
}

func (_m *MockGitMetadataReader) EXPECT() *MockGitMetadataReader_Expecter {
	return &MockGitMetadataReader_Expecter{mock: &_m.Mock}
}

// CurrentBranch provides a mock function for the type MockGitMetadataReader
func (_mock *MockGitMetadataReader) CurrentBranch(repoPath string) (string, error) {
	ret := _mock.Called(repoPath)

	if len(ret) == 0 {
		panic("no return value specified for CurrentBranch")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) (string, error)); ok {
		return returnFunc(repoPath)
	}
	if returnFunc, ok := ret.Get(0).(func(string) string); ok {
		r0 = returnFunc(repoPath)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(repoPath)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockGitMetadataReader_CurrentBranch_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CurrentBranch'
type MockGitMetadataReader_CurrentBranch_Call struct {
	*mock.Call
}

// CurrentBranch is a helper method to define mock.On call
//   - repoPath string
func (_e *MockGitMetadataReader_Expecter) CurrentBranch(repoPath interface{}) *MockGitMetadataReader_CurrentBranch_Call {
	return &MockGitMetadataReader_CurrentBranch_Call{Call: _e.mock.On("CurrentBranch", repoPath)}
}

func (_c *MockGitMetadataReader_CurrentBranch_Call) Run(run func(repoPath string)) *MockGitMetadataReader_CurrentBranch_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockGitMetadataReader_CurrentBranch_Call) Return(s string, err error) *MockGitMetadataReader_CurrentBranch_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *MockGitMetadataReader_CurrentBranch_Call) RunAndReturn(run func(repoPath string) (string, error)) *MockGitMetadataReader_CurrentBranch_Call {
	_c.Call.Return(run)
	return _c
}

// DefaultBranch provides a mock function for the type MockGitMetadataReader
func (_mock *MockGitMetadataReader) DefaultBranch(repoPath string) (string, error) {
	ret := _mock.Called(repoPath)

	if len(ret) == 0 {
		panic("no return value specified for DefaultBranch")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) (string, error)); ok {
		return returnFunc(repoPath)
	}
	if returnFunc, ok := ret.Get(0).(func(string) string); ok {
		r0 = returnFunc(repoPath)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(repoPath)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockGitMetadataReader_DefaultBranch_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DefaultBranch'
type MockGitMetadataReader_DefaultBranch_Call struct {
	*mock.Call
}

// DefaultBranch is a helper method to define mock.On call
//   - repoPath string
func (_e *MockGitMetadataReader_Expecter) DefaultBranch(repoPath interface{}) *MockGitMetadataReader_DefaultBranch_Call {
	return &MockGitMetadataReader_DefaultBranch_Call{Call: _e.mock.On("DefaultBranch", repoPath)}
}

func (_c *MockGitMetadataReader_DefaultBranch_Call) Run(run func(repoPath string)) *MockGitMetadataReader_DefaultBranch_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockGitMetadataReader_DefaultBranch_Call) Return(s string, err error) *MockGitMetadataReader_DefaultBranch_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *MockGitMetadataReader_DefaultBranch_Call) RunAndReturn(run func(repoPath string) (string, error)) *MockGitMetadataReader_DefaultBranch_Call {
	_c.Call.Return(run)
	return _c
}

// HeadSHA provides a mock function for the type MockGitMetadataReader
func (_mock *MockGitMetadataReader) HeadSHA(repoPath string) (string, error) {
	ret := _mock.Called(repoPath)

	if len(ret) == 0 {
		panic("no return value specified for HeadSHA")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) (string, error)); ok {
		return returnFunc(repoPath)
	}
	if returnFunc, ok := ret.Get(0).(func(string) string); ok {
		r0 = returnFunc(repoPath)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(repoPath)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockGitMetadataReader_HeadSHA_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'HeadSHA'
type MockGitMetadataReader_HeadSHA_Call struct {
	*mock.Call
}

// HeadSHA is a helper method to define mock.On call
//   - repoPath string
func (_e *MockGitMetadataReader_Expecter) HeadSHA(repoPath interface{}) *MockGitMetadataReader_HeadSHA_Call {
	return &MockGitMetadataReader_HeadSHA_Call{Call: _e.mock.On("HeadSHA", repoPath)}
}

func (_c *MockGitMetadataReader_HeadSHA_Call) Run(run func(repoPath string)) *MockGitMetadataReader_HeadSHA_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockGitMetadataReader_HeadSHA_Call) Return(s string, err error) *MockGitMetadataReader_HeadSHA_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *MockGitMetadataReader_HeadSHA_Call) RunAndReturn(run func(repoPath string) (string, error)) *MockGitMetadataReader_HeadSHA_Call {
	_c.Call.Return(run)
	return _c
}

// MergeBase provides a mock function for the type MockGitMetadataReader
func (_mock *MockGitMetadataReader) MergeBase(repoPath string, baseRef string, headRef string) (string, error) {
	ret := _mock.Called(repoPath, baseRef, headRef)

	if len(ret) == 0 {
		panic("no return value specified for MergeBase")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string, string, string) (string, error)); ok {
		return returnFunc(repoPath, baseRef, headRef)
	}
	if returnFunc, ok := ret.Get(0).(func(string, string, string) string); ok {
		r0 = returnFunc(repoPath, baseRef, headRef)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(string, string, string) error); ok {
		r1 = returnFunc(repoPath, baseRef, headRef)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockGitMetadataReader_MergeBase_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'MergeBase'
type MockGitMetadataReader_MergeBase_Call struct {
	*mock.Call
}

// MergeBase is a helper method to define mock.On call
//   - repoPath string
//   - baseRef string
//   - headRef string
func (_e *MockGitMetadataReader_Expecter) MergeBase(repoPath interface{}, baseRef interface{}, headRef interface{}) *MockGitMetadataReader_MergeBase_Call {
	return &MockGitMetadataReader_MergeBase_Call{Call: _e.mock.On("MergeBase", repoPath, baseRef, headRef)}
}

func (_c *MockGitMetadataReader_MergeBase_Call) Run(run func(repoPath string, baseRef string, headRef string)) *MockGitMetadataReader_MergeBase_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockGitMetadataReader_MergeBase_Call) Return(s string, err error) *MockGitMetadataReader_MergeBase_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *MockGitMetadataReader_MergeBase_Call) RunAndReturn(run func(repoPath string, baseRef string, headRef string) (string, error)) *MockGitMetadataReader_MergeBase_Call {
	_c.Call.Return(run)
	return _c
}

// Remotes provides a mock function for the type MockGitMetadataReader
func (_mock *MockGitMetadataReader) Remotes(repoPath string) ([]ports.GitRemoteInfo, error) {
	ret := _mock.Called(repoPath)

	if len(ret) == 0 {
		panic("no return value specified for Remotes")
	}

	var r0 []ports.GitRemoteInfo
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) ([]ports.GitRemoteInfo, error)); ok {
		return returnFunc(repoPath)
	}
	if returnFunc, ok := ret.Get(0).(func(string) []ports.GitRemoteInfo); ok {
		r0 = returnFunc(repoPath)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]ports.GitRemoteInfo)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(repoPath)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockGitMetadataReader_Remotes_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Remotes'
type MockGitMetadataReader_Remotes_Call struct {
	*mock.Call
}

// Remotes is a helper method to define mock.On call
//   - repoPath string
func (_e *MockGitMetadataReader_Expecter) Remotes(repoPath interface{}) *MockGitMetadataReader_Remotes_Call {
	return &MockGitMetadataReader_Remotes_Call{Call: _e.mock.On("Remotes", repoPath)}
}

func (_c *MockGitMetadataReader_Remotes_Call) Run(run func(repoPath string)) *MockGitMetadataReader_Remotes_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockGitMetadataReader_Remotes_Call) Return(gitRemoteInfos []ports.GitRemoteInfo, err error) *MockGitMetadataReader_Remotes_Call {
	_c.Call.Return(gitRemoteInfos, err)
	return _c
}

func (_c *MockGitMetadataReader_Remotes_Call) RunAndReturn(run func(repoPath string) ([]ports.GitRemoteInfo, error)) *MockGitMetadataReader_Remotes_Call {
	_c.Call.Return(run)
	return _c
}

// ResolveRevision provides a mock function for the type MockGitMetadataReader
func (_mock *MockGitMetadataReader) ResolveRevision(repoPath string, revision string) (string, error) {
	ret := _mock.Called(repoPath, revision)

	if len(ret) == 0 {
		panic("no return value specified for ResolveRevision")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string, string) (string, error)); ok {
		return returnFunc(repoPath, revision)
	}
	if returnFunc, ok := ret.Get(0).(func(string, string) string); ok {
		r0 = returnFunc(repoPath, revision)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(string, string) error); ok {
		r1 = returnFunc(repoPath, revision)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockGitMetadataReader_ResolveRevision_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ResolveRevision'
type MockGitMetadataReader_ResolveRevision_Call struct {
	*mock.Call
}

// ResolveRevision is a helper method to define mock.On call
//   - repoPath string
//   - revision string
func (_e *MockGitMetadataReader_Expecter) ResolveRevision(repoPath interface{}, revision interface{}) *MockGitMetadataReader_ResolveRevision_Call {
	return &MockGitMetadataReader_ResolveRevision_Call{Call: _e.mock.On("ResolveRevision", repoPath, revision)}
}

func (_c *MockGitMetadataReader_ResolveRevision_Call) Run(run func(repoPath string, revision string)) *MockGitMetadataReader_ResolveRevision_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockGitMetadataReader_ResolveRevision_Call) Return(s string, err error) *MockGitMetadataReader_ResolveRevision_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *MockGitMetadataReader_ResolveRevision_Call) RunAndReturn(run func(repoPath string, revision string) (string, error)) *MockGitMetadataReader_ResolveRevision_Call {
	_c.Call.Return(run)
	return _c
}

// WorktreeRoot provides a mock function for the type MockGitMetadataReader
func (_mock *MockGitMetadataReader) WorktreeRoot(repoPath string) (string, error) {
	ret := _mock.Called(repoPath)

	if len(ret) == 0 {
		panic("no return value specified for WorktreeRoot")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) (string, error)); ok {
		return returnFunc(repoPath)
	}
	if returnFunc, ok := ret.Get(0).(func(string) string); ok {
		r0 = returnFunc(repoPath)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(repoPath)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockGitMetadataReader_WorktreeRoot_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'WorktreeRoot'
type MockGitMetadataReader_WorktreeRoot_Call struct {
	*mock.Call
}

// WorktreeRoot is a helper method to define mock.On call
//   - repoPath string
func (_e *MockGitMetadataReader_Expecter) WorktreeRoot(repoPath interface{}) *MockGitMetadataReader_WorktreeRoot_Call {
	return &MockGitMetadataReader_WorktreeRoot_Call{Call: _e.mock.On("WorktreeRoot", repoPath)}
}

func (_c *MockGitMetadataReader_WorktreeRoot_Call) Run(run func(repoPath string)) *MockGitMetadataReader_WorktreeRoot_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockGitMetadataReader_WorktreeRoot_Call) Return(s string, err error) *MockGitMetadataReader_WorktreeRoot_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *MockGitMetadataReader_WorktreeRoot_Call) RunAndReturn(run func(repoPath string) (string, error)) *MockGitMetadataReader_WorktreeRoot_Call {
	_c.Call.Return(run)
	return _c
}
