// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	mock "github.com/stretchr/testify/mock"
)

// NewMockGitDiffLoader creates a new instance of MockGitDiffLoader. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockGitDiffLoader(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockGitDiffLoader {
	mock := &MockGitDiffLoader{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockGitDiffLoader is an autogenerated mock type for the GitDiffLoader type
type MockGitDiffLoader struct {
	mock.Mock
}

type MockGitDiffLoader_Expecter struct {
	mock *mock.Mock
}

func (_m *MockGitDiffLoader) EXPECT() *MockGitDiffLoader_Expecter {
	return &MockGitDiffLoader_Expecter{mock: &_m.Mock}
}

// LoadBranchDiff provides a mock function for the type MockGitDiffLoader
func (_mock *MockGitDiffLoader) LoadBranchDiff(repoPath string, baseBranch string) (string, error) {
	ret := _mock.Called(repoPath, baseBranch)

	if len(ret) == 0 {
		panic("no return value specified for LoadBranchDiff")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string, string) (string, error)); ok {
		return returnFunc(repoPath, baseBranch)
	}
	if returnFunc, ok := ret.Get(0).(func(string, string) string); ok {
		r0 = returnFunc(repoPath, baseBranch)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(string, string) error); ok {
		r1 = returnFunc(repoPath, baseBranch)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockGitDiffLoader_LoadBranchDiff_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'LoadBranchDiff'
type MockGitDiffLoader_LoadBranchDiff_Call struct {
	*mock.Call
}

// LoadBranchDiff is a helper method to define mock.On call
//   - repoPath string
//   - baseBranch string
func (_e *MockGitDiffLoader_Expecter) LoadBranchDiff(repoPath interface{}, baseBranch interface{}) *MockGitDiffLoader_LoadBranchDiff_Call {
	return &MockGitDiffLoader_LoadBranchDiff_Call{Call: _e.mock.On("LoadBranchDiff", repoPath, baseBranch)}
}

func (_c *MockGitDiffLoader_LoadBranchDiff_Call) Run(run func(repoPath string, baseBranch string)) *MockGitDiffLoader_LoadBranchDiff_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockGitDiffLoader_LoadBranchDiff_Call) Return(s string, err error) *MockGitDiffLoader_LoadBranchDiff_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *MockGitDiffLoader_LoadBranchDiff_Call) RunAndReturn(run func(repoPath string, baseBranch string) (string, error)) *MockGitDiffLoader_LoadBranchDiff_Call {
	_c.Call.Return(run)
	return _c
}
