// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"
	"ero/internal/ports"

	mock "github.com/stretchr/testify/mock"
)

// NewMockPluginLifecycle creates a new instance of MockPluginLifecycle. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockPluginLifecycle(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockPluginLifecycle {
	mock := &MockPluginLifecycle{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockPluginLifecycle is an autogenerated mock type for the PluginLifecycle type
type MockPluginLifecycle struct {
	mock.Mock
}

type MockPluginLifecycle_Expecter struct {
	mock *mock.Mock
}

func (_m *MockPluginLifecycle) EXPECT() *MockPluginLifecycle_Expecter {
	return &MockPluginLifecycle_Expecter{mock: &_m.Mock}
}

// Install provides a mock function for the type MockPluginLifecycle
func (_mock *MockPluginLifecycle) Install(ctx context.Context, source string) (ports.PluginInstallResult, error) {
	ret := _mock.Called(ctx, source)

	if len(ret) == 0 {
		panic("no return value specified for Install")
	}

	var r0 ports.PluginInstallResult
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (ports.PluginInstallResult, error)); ok {
		return returnFunc(ctx, source)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) ports.PluginInstallResult); ok {
		r0 = returnFunc(ctx, source)
	} else {
		r0 = ret.Get(0).(ports.PluginInstallResult)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, source)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockPluginLifecycle_Install_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Install'
type MockPluginLifecycle_Install_Call struct {
	*mock.Call
}

// Install is a helper method to define mock.On call
//   - ctx context.Context
//   - source string
func (_e *MockPluginLifecycle_Expecter) Install(ctx interface{}, source interface{}) *MockPluginLifecycle_Install_Call {
	return &MockPluginLifecycle_Install_Call{Call: _e.mock.On("Install", ctx, source)}
}

func (_c *MockPluginLifecycle_Install_Call) Run(run func(ctx context.Context, source string)) *MockPluginLifecycle_Install_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockPluginLifecycle_Install_Call) Return(pluginInstallResult ports.PluginInstallResult, err error) *MockPluginLifecycle_Install_Call {
	_c.Call.Return(pluginInstallResult, err)
	return _c
}

func (_c *MockPluginLifecycle_Install_Call) RunAndReturn(run func(ctx context.Context, source string) (ports.PluginInstallResult, error)) *MockPluginLifecycle_Install_Call {
	_c.Call.Return(run)
	return _c
}

// List provides a mock function for the type MockPluginLifecycle
func (_mock *MockPluginLifecycle) List(ctx context.Context) ([]ports.InstalledPlugin, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 []ports.InstalledPlugin
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) ([]ports.InstalledPlugin, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) []ports.InstalledPlugin); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]ports.InstalledPlugin)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockPluginLifecycle_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type MockPluginLifecycle_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockPluginLifecycle_Expecter) List(ctx interface{}) *MockPluginLifecycle_List_Call {
	return &MockPluginLifecycle_List_Call{Call: _e.mock.On("List", ctx)}
}

func (_c *MockPluginLifecycle_List_Call) Run(run func(ctx context.Context)) *MockPluginLifecycle_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockPluginLifecycle_List_Call) Return(installedPlugins []ports.InstalledPlugin, err error) *MockPluginLifecycle_List_Call {
	_c.Call.Return(installedPlugins, err)
	return _c
}

func (_c *MockPluginLifecycle_List_Call) RunAndReturn(run func(ctx context.Context) ([]ports.InstalledPlugin, error)) *MockPluginLifecycle_List_Call {
	_c.Call.Return(run)
	return _c
}

// Remove provides a mock function for the type MockPluginLifecycle
func (_mock *MockPluginLifecycle) Remove(ctx context.Context, nameOrSource string) (ports.PluginRemoveResult, error) {
	ret := _mock.Called(ctx, nameOrSource)

	if len(ret) == 0 {
		panic("no return value specified for Remove")
	}

	var r0 ports.PluginRemoveResult
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (ports.PluginRemoveResult, error)); ok {
		return returnFunc(ctx, nameOrSource)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) ports.PluginRemoveResult); ok {
		r0 = returnFunc(ctx, nameOrSource)
	} else {
		r0 = ret.Get(0).(ports.PluginRemoveResult)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, nameOrSource)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockPluginLifecycle_Remove_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Remove'
type MockPluginLifecycle_Remove_Call struct {
	*mock.Call
}

// Remove is a helper method to define mock.On call
//   - ctx context.Context
//   - nameOrSource string
func (_e *MockPluginLifecycle_Expecter) Remove(ctx interface{}, nameOrSource interface{}) *MockPluginLifecycle_Remove_Call {
	return &MockPluginLifecycle_Remove_Call{Call: _e.mock.On("Remove", ctx, nameOrSource)}
}

func (_c *MockPluginLifecycle_Remove_Call) Run(run func(ctx context.Context, nameOrSource string)) *MockPluginLifecycle_Remove_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockPluginLifecycle_Remove_Call) Return(pluginRemoveResult ports.PluginRemoveResult, err error) *MockPluginLifecycle_Remove_Call {
	_c.Call.Return(pluginRemoveResult, err)
	return _c
}

func (_c *MockPluginLifecycle_Remove_Call) RunAndReturn(run func(ctx context.Context, nameOrSource string) (ports.PluginRemoveResult, error)) *MockPluginLifecycle_Remove_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function for the type MockPluginLifecycle
func (_mock *MockPluginLifecycle) Update(ctx context.Context, source string) ([]ports.PluginUpdateResult, error) {
	ret := _mock.Called(ctx, source)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 []ports.PluginUpdateResult
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) ([]ports.PluginUpdateResult, error)); ok {
		return returnFunc(ctx, source)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) []ports.PluginUpdateResult); ok {
		r0 = returnFunc(ctx, source)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]ports.PluginUpdateResult)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, source)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockPluginLifecycle_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockPluginLifecycle_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - source string
func (_e *MockPluginLifecycle_Expecter) Update(ctx interface{}, source interface{}) *MockPluginLifecycle_Update_Call {
	return &MockPluginLifecycle_Update_Call{Call: _e.mock.On("Update", ctx, source)}
}

func (_c *MockPluginLifecycle_Update_Call) Run(run func(ctx context.Context, source string)) *MockPluginLifecycle_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockPluginLifecycle_Update_Call) Return(pluginUpdateResults []ports.PluginUpdateResult, err error) *MockPluginLifecycle_Update_Call {
	_c.Call.Return(pluginUpdateResults, err)
	return _c
}

func (_c *MockPluginLifecycle_Update_Call) RunAndReturn(run func(ctx context.Context, source string) ([]ports.PluginUpdateResult, error)) *MockPluginLifecycle_Update_Call {
	_c.Call.Return(run)
	return _c
}
