// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"
	"ero/internal/ports"

	mock "github.com/stretchr/testify/mock"
)

// NewMockPluginRegistry creates a new instance of MockPluginRegistry. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockPluginRegistry(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockPluginRegistry {
	mock := &MockPluginRegistry{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockPluginRegistry is an autogenerated mock type for the PluginRegistry type
type MockPluginRegistry struct {
	mock.Mock
}

type MockPluginRegistry_Expecter struct {
	mock *mock.Mock
}

func (_m *MockPluginRegistry) EXPECT() *MockPluginRegistry_Expecter {
	return &MockPluginRegistry_Expecter{mock: &_m.Mock}
}

// InstalledPlugins provides a mock function for the type MockPluginRegistry
func (_mock *MockPluginRegistry) InstalledPlugins(ctx context.Context) ([]ports.PluginDescriptor, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for InstalledPlugins")
	}

	var r0 []ports.PluginDescriptor
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) ([]ports.PluginDescriptor, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) []ports.PluginDescriptor); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]ports.PluginDescriptor)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockPluginRegistry_InstalledPlugins_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'InstalledPlugins'
type MockPluginRegistry_InstalledPlugins_Call struct {
	*mock.Call
}

// InstalledPlugins is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockPluginRegistry_Expecter) InstalledPlugins(ctx interface{}) *MockPluginRegistry_InstalledPlugins_Call {
	return &MockPluginRegistry_InstalledPlugins_Call{Call: _e.mock.On("InstalledPlugins", ctx)}
}

func (_c *MockPluginRegistry_InstalledPlugins_Call) Run(run func(ctx context.Context)) *MockPluginRegistry_InstalledPlugins_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockPluginRegistry_InstalledPlugins_Call) Return(pluginDescriptors []ports.PluginDescriptor, err error) *MockPluginRegistry_InstalledPlugins_Call {
	_c.Call.Return(pluginDescriptors, err)
	return _c
}

func (_c *MockPluginRegistry_InstalledPlugins_Call) RunAndReturn(run func(ctx context.Context) ([]ports.PluginDescriptor, error)) *MockPluginRegistry_InstalledPlugins_Call {
	_c.Call.Return(run)
	return _c
}
