// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"
	"ero/internal/core"

	mock "github.com/stretchr/testify/mock"
)

// NewMockReviewProviderClient creates a new instance of MockReviewProviderClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockReviewProviderClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockReviewProviderClient {
	mock := &MockReviewProviderClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockReviewProviderClient is an autogenerated mock type for the ReviewProviderClient type
type MockReviewProviderClient struct {
	mock.Mock
}

type MockReviewProviderClient_Expecter struct {
	mock *mock.Mock
}

func (_m *MockReviewProviderClient) EXPECT() *MockReviewProviderClient_Expecter {
	return &MockReviewProviderClient_Expecter{mock: &_m.Mock}
}

// Close provides a mock function for the type MockReviewProviderClient
func (_mock *MockReviewProviderClient) Close() error {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Close")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func() error); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockReviewProviderClient_Close_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Close'
type MockReviewProviderClient_Close_Call struct {
	*mock.Call
}

// Close is a helper method to define mock.On call
func (_e *MockReviewProviderClient_Expecter) Close() *MockReviewProviderClient_Close_Call {
	return &MockReviewProviderClient_Close_Call{Call: _e.mock.On("Close")}
}

func (_c *MockReviewProviderClient_Close_Call) Run(run func()) *MockReviewProviderClient_Close_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockReviewProviderClient_Close_Call) Return(err error) *MockReviewProviderClient_Close_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockReviewProviderClient_Close_Call) RunAndReturn(run func() error) *MockReviewProviderClient_Close_Call {
	_c.Call.Return(run)
	return _c
}

// DetectContext provides a mock function for the type MockReviewProviderClient
func (_mock *MockReviewProviderClient) DetectContext(ctx context.Context, review core.ReviewContext) (core.DetectionResult, error) {
	ret := _mock.Called(ctx, review)

	if len(ret) == 0 {
		panic("no return value specified for DetectContext")
	}

	var r0 core.DetectionResult
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, core.ReviewContext) (core.DetectionResult, error)); ok {
		return returnFunc(ctx, review)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, core.ReviewContext) core.DetectionResult); ok {
		r0 = returnFunc(ctx, review)
	} else {
		r0 = ret.Get(0).(core.DetectionResult)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, core.ReviewContext) error); ok {
		r1 = returnFunc(ctx, review)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockReviewProviderClient_DetectContext_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DetectContext'
type MockReviewProviderClient_DetectContext_Call struct {
	*mock.Call
}

// DetectContext is a helper method to define mock.On call
//   - ctx context.Context
//   - review core.ReviewContext
func (_e *MockReviewProviderClient_Expecter) DetectContext(ctx interface{}, review interface{}) *MockReviewProviderClient_DetectContext_Call {
	return &MockReviewProviderClient_DetectContext_Call{Call: _e.mock.On("DetectContext", ctx, review)}
}

func (_c *MockReviewProviderClient_DetectContext_Call) Run(run func(ctx context.Context, review core.ReviewContext)) *MockReviewProviderClient_DetectContext_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 core.ReviewContext
		if args[1] != nil {
			arg1 = args[1].(core.ReviewContext)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockReviewProviderClient_DetectContext_Call) Return(detectionResult core.DetectionResult, err error) *MockReviewProviderClient_DetectContext_Call {
	_c.Call.Return(detectionResult, err)
	return _c
}

func (_c *MockReviewProviderClient_DetectContext_Call) RunAndReturn(run func(ctx context.Context, review core.ReviewContext) (core.DetectionResult, error)) *MockReviewProviderClient_DetectContext_Call {
	_c.Call.Return(run)
	return _c
}

// Initialize provides a mock function for the type MockReviewProviderClient
func (_mock *MockReviewProviderClient) Initialize(ctx context.Context) (core.ReviewProviderInfo, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Initialize")
	}

	var r0 core.ReviewProviderInfo
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) (core.ReviewProviderInfo, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) core.ReviewProviderInfo); ok {
		r0 = returnFunc(ctx)
	} else {
		r0 = ret.Get(0).(core.ReviewProviderInfo)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockReviewProviderClient_Initialize_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Initialize'
type MockReviewProviderClient_Initialize_Call struct {
	*mock.Call
}

// Initialize is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockReviewProviderClient_Expecter) Initialize(ctx interface{}) *MockReviewProviderClient_Initialize_Call {
	return &MockReviewProviderClient_Initialize_Call{Call: _e.mock.On("Initialize", ctx)}
}

func (_c *MockReviewProviderClient_Initialize_Call) Run(run func(ctx context.Context)) *MockReviewProviderClient_Initialize_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockReviewProviderClient_Initialize_Call) Return(reviewProviderInfo core.ReviewProviderInfo, err error) *MockReviewProviderClient_Initialize_Call {
	_c.Call.Return(reviewProviderInfo, err)
	return _c
}

func (_c *MockReviewProviderClient_Initialize_Call) RunAndReturn(run func(ctx context.Context) (core.ReviewProviderInfo, error)) *MockReviewProviderClient_Initialize_Call {
	_c.Call.Return(run)
	return _c
}

// LoadRemoteThreads provides a mock function for the type MockReviewProviderClient
func (_mock *MockReviewProviderClient) LoadRemoteThreads(ctx context.Context, review core.ReviewContext) ([]core.RemoteReviewThread, error) {
	ret := _mock.Called(ctx, review)

	if len(ret) == 0 {
		panic("no return value specified for LoadRemoteThreads")
	}

	var r0 []core.RemoteReviewThread
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, core.ReviewContext) ([]core.RemoteReviewThread, error)); ok {
		return returnFunc(ctx, review)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, core.ReviewContext) []core.RemoteReviewThread); ok {
		r0 = returnFunc(ctx, review)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]core.RemoteReviewThread)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, core.ReviewContext) error); ok {
		r1 = returnFunc(ctx, review)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockReviewProviderClient_LoadRemoteThreads_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'LoadRemoteThreads'
type MockReviewProviderClient_LoadRemoteThreads_Call struct {
	*mock.Call
}

// LoadRemoteThreads is a helper method to define mock.On call
//   - ctx context.Context
//   - review core.ReviewContext
func (_e *MockReviewProviderClient_Expecter) LoadRemoteThreads(ctx interface{}, review interface{}) *MockReviewProviderClient_LoadRemoteThreads_Call {
	return &MockReviewProviderClient_LoadRemoteThreads_Call{Call: _e.mock.On("LoadRemoteThreads", ctx, review)}
}

func (_c *MockReviewProviderClient_LoadRemoteThreads_Call) Run(run func(ctx context.Context, review core.ReviewContext)) *MockReviewProviderClient_LoadRemoteThreads_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 core.ReviewContext
		if args[1] != nil {
			arg1 = args[1].(core.ReviewContext)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockReviewProviderClient_LoadRemoteThreads_Call) Return(remoteReviewThreads []core.RemoteReviewThread, err error) *MockReviewProviderClient_LoadRemoteThreads_Call {
	_c.Call.Return(remoteReviewThreads, err)
	return _c
}

func (_c *MockReviewProviderClient_LoadRemoteThreads_Call) RunAndReturn(run func(ctx context.Context, review core.ReviewContext) ([]core.RemoteReviewThread, error)) *MockReviewProviderClient_LoadRemoteThreads_Call {
	_c.Call.Return(run)
	return _c
}

// PublishReview provides a mock function for the type MockReviewProviderClient
func (_mock *MockReviewProviderClient) PublishReview(ctx context.Context, request core.PublishReviewRequest) (core.PublishReviewResult, error) {
	ret := _mock.Called(ctx, request)

	if len(ret) == 0 {
		panic("no return value specified for PublishReview")
	}

	var r0 core.PublishReviewResult
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, core.PublishReviewRequest) (core.PublishReviewResult, error)); ok {
		return returnFunc(ctx, request)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, core.PublishReviewRequest) core.PublishReviewResult); ok {
		r0 = returnFunc(ctx, request)
	} else {
		r0 = ret.Get(0).(core.PublishReviewResult)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, core.PublishReviewRequest) error); ok {
		r1 = returnFunc(ctx, request)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockReviewProviderClient_PublishReview_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PublishReview'
type MockReviewProviderClient_PublishReview_Call struct {
	*mock.Call
}

// PublishReview is a helper method to define mock.On call
//   - ctx context.Context
//   - request core.PublishReviewRequest
func (_e *MockReviewProviderClient_Expecter) PublishReview(ctx interface{}, request interface{}) *MockReviewProviderClient_PublishReview_Call {
	return &MockReviewProviderClient_PublishReview_Call{Call: _e.mock.On("PublishReview", ctx, request)}
}

func (_c *MockReviewProviderClient_PublishReview_Call) Run(run func(ctx context.Context, request core.PublishReviewRequest)) *MockReviewProviderClient_PublishReview_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 core.PublishReviewRequest
		if args[1] != nil {
			arg1 = args[1].(core.PublishReviewRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockReviewProviderClient_PublishReview_Call) Return(publishReviewResult core.PublishReviewResult, err error) *MockReviewProviderClient_PublishReview_Call {
	_c.Call.Return(publishReviewResult, err)
	return _c
}

func (_c *MockReviewProviderClient_PublishReview_Call) RunAndReturn(run func(ctx context.Context, request core.PublishReviewRequest) (core.PublishReviewResult, error)) *MockReviewProviderClient_PublishReview_Call {
	_c.Call.Return(run)
	return _c
}
