// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	mock "github.com/stretchr/testify/mock"
)

// NewMockStartupStateReader creates a new instance of MockStartupStateReader. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockStartupStateReader[T any](t interface {
	mock.TestingT
	Cleanup(func())
}) *MockStartupStateReader[T] {
	mock := &MockStartupStateReader[T]{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockStartupStateReader is an autogenerated mock type for the StartupStateReader type
type MockStartupStateReader[T any] struct {
	mock.Mock
}

type MockStartupStateReader_Expecter[T any] struct {
	mock *mock.Mock
}

func (_m *MockStartupStateReader[T]) EXPECT() *MockStartupStateReader_Expecter[T] {
	return &MockStartupStateReader_Expecter[T]{mock: &_m.Mock}
}

// ReadStartupState provides a mock function for the type MockStartupStateReader
func (_mock *MockStartupStateReader[T]) ReadStartupState(repoPath string) (T, error) {
	ret := _mock.Called(repoPath)

	if len(ret) == 0 {
		panic("no return value specified for ReadStartupState")
	}

	var r0 T
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) (T, error)); ok {
		return returnFunc(repoPath)
	}
	if returnFunc, ok := ret.Get(0).(func(string) T); ok {
		r0 = returnFunc(repoPath)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(T)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(repoPath)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockStartupStateReader_ReadStartupState_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ReadStartupState'
type MockStartupStateReader_ReadStartupState_Call[T any] struct {
	*mock.Call
}

// ReadStartupState is a helper method to define mock.On call
//   - repoPath string
func (_e *MockStartupStateReader_Expecter[T]) ReadStartupState(repoPath interface{}) *MockStartupStateReader_ReadStartupState_Call[T] {
	return &MockStartupStateReader_ReadStartupState_Call[T]{Call: _e.mock.On("ReadStartupState", repoPath)}
}

func (_c *MockStartupStateReader_ReadStartupState_Call[T]) Run(run func(repoPath string)) *MockStartupStateReader_ReadStartupState_Call[T] {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockStartupStateReader_ReadStartupState_Call[T]) Return(v T, err error) *MockStartupStateReader_ReadStartupState_Call[T] {
	_c.Call.Return(v, err)
	return _c
}

func (_c *MockStartupStateReader_ReadStartupState_Call[T]) RunAndReturn(run func(repoPath string) (T, error)) *MockStartupStateReader_ReadStartupState_Call[T] {
	_c.Call.Return(run)
	return _c
}
