// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"tgdiff/internal/core"

	mock "github.com/stretchr/testify/mock"
)

// NewMockSyntaxTokenizer creates a new instance of MockSyntaxTokenizer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockSyntaxTokenizer(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockSyntaxTokenizer {
	mock := &MockSyntaxTokenizer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockSyntaxTokenizer is an autogenerated mock type for the SyntaxTokenizer type
type MockSyntaxTokenizer struct {
	mock.Mock
}

type MockSyntaxTokenizer_Expecter struct {
	mock *mock.Mock
}

func (_m *MockSyntaxTokenizer) EXPECT() *MockSyntaxTokenizer_Expecter {
	return &MockSyntaxTokenizer_Expecter{mock: &_m.Mock}
}

// Language provides a mock function for the type MockSyntaxTokenizer
func (_mock *MockSyntaxTokenizer) Language(filename string) string {
	ret := _mock.Called(filename)

	if len(ret) == 0 {
		panic("no return value specified for Language")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func(string) string); ok {
		r0 = returnFunc(filename)
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// MockSyntaxTokenizer_Language_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Language'
type MockSyntaxTokenizer_Language_Call struct {
	*mock.Call
}

// Language is a helper method to define mock.On call
//   - filename string
func (_e *MockSyntaxTokenizer_Expecter) Language(filename interface{}) *MockSyntaxTokenizer_Language_Call {
	return &MockSyntaxTokenizer_Language_Call{Call: _e.mock.On("Language", filename)}
}

func (_c *MockSyntaxTokenizer_Language_Call) Run(run func(filename string)) *MockSyntaxTokenizer_Language_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockSyntaxTokenizer_Language_Call) Return(s string) *MockSyntaxTokenizer_Language_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *MockSyntaxTokenizer_Language_Call) RunAndReturn(run func(filename string) string) *MockSyntaxTokenizer_Language_Call {
	_c.Call.Return(run)
	return _c
}

// Tokenize provides a mock function for the type MockSyntaxTokenizer
func (_mock *MockSyntaxTokenizer) Tokenize(filename string, lines []string) ([][]core.SyntaxToken, error) {
	ret := _mock.Called(filename, lines)

	if len(ret) == 0 {
		panic("no return value specified for Tokenize")
	}

	var r0 [][]core.SyntaxToken
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string, []string) ([][]core.SyntaxToken, error)); ok {
		return returnFunc(filename, lines)
	}
	if returnFunc, ok := ret.Get(0).(func(string, []string) [][]core.SyntaxToken); ok {
		r0 = returnFunc(filename, lines)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([][]core.SyntaxToken)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string, []string) error); ok {
		r1 = returnFunc(filename, lines)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockSyntaxTokenizer_Tokenize_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Tokenize'
type MockSyntaxTokenizer_Tokenize_Call struct {
	*mock.Call
}

// Tokenize is a helper method to define mock.On call
//   - filename string
//   - lines []string
func (_e *MockSyntaxTokenizer_Expecter) Tokenize(filename interface{}, lines interface{}) *MockSyntaxTokenizer_Tokenize_Call {
	return &MockSyntaxTokenizer_Tokenize_Call{Call: _e.mock.On("Tokenize", filename, lines)}
}

func (_c *MockSyntaxTokenizer_Tokenize_Call) Run(run func(filename string, lines []string)) *MockSyntaxTokenizer_Tokenize_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 []string
		if args[1] != nil {
			arg1 = args[1].([]string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockSyntaxTokenizer_Tokenize_Call) Return(syntaxTokenss [][]core.SyntaxToken, err error) *MockSyntaxTokenizer_Tokenize_Call {
	_c.Call.Return(syntaxTokenss, err)
	return _c
}

func (_c *MockSyntaxTokenizer_Tokenize_Call) RunAndReturn(run func(filename string, lines []string) ([][]core.SyntaxToken, error)) *MockSyntaxTokenizer_Tokenize_Call {
	_c.Call.Return(run)
	return _c
}
