// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	mock "github.com/stretchr/testify/mock"
)

// NewMockTerminal creates a new instance of MockTerminal. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockTerminal(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockTerminal {
	mock := &MockTerminal{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockTerminal is an autogenerated mock type for the Terminal type
type MockTerminal struct {
	mock.Mock
}

type MockTerminal_Expecter struct {
	mock *mock.Mock
}

func (_m *MockTerminal) EXPECT() *MockTerminal_Expecter {
	return &MockTerminal_Expecter{mock: &_m.Mock}
}

// SupportsNerdFont provides a mock function for the type MockTerminal
func (_mock *MockTerminal) SupportsNerdFont() bool {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for SupportsNerdFont")
	}

	var r0 bool
	if returnFunc, ok := ret.Get(0).(func() bool); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(bool)
	}
	return r0
}

// MockTerminal_SupportsNerdFont_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SupportsNerdFont'
type MockTerminal_SupportsNerdFont_Call struct {
	*mock.Call
}

// SupportsNerdFont is a helper method to define mock.On call
func (_e *MockTerminal_Expecter) SupportsNerdFont() *MockTerminal_SupportsNerdFont_Call {
	return &MockTerminal_SupportsNerdFont_Call{Call: _e.mock.On("SupportsNerdFont")}
}

func (_c *MockTerminal_SupportsNerdFont_Call) Run(run func()) *MockTerminal_SupportsNerdFont_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockTerminal_SupportsNerdFont_Call) Return(b bool) *MockTerminal_SupportsNerdFont_Call {
	_c.Call.Return(b)
	return _c
}

func (_c *MockTerminal_SupportsNerdFont_Call) RunAndReturn(run func() bool) *MockTerminal_SupportsNerdFont_Call {
	_c.Call.Return(run)
	return _c
}
